global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'catcat-production'
    replica: '1'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # CatCat API metrics
  - job_name: 'catcat-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (using postgres_exporter if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics (using redis_exporter if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # NATS metrics
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/varz'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

